### ISSUE TITLE
ShowIf not working properly with List<T>

### ISSUE THREAD

**Issue by GlennQuintyn** [Rhinox-Training/rhinox-guiutils#36]
GUIUtils: v2.7.0
Litghspeed: v1.5.5

Using the following code:

```cs
        [Header("Bounding box settings")]
        [SerializeField] private bool _useCollidersInsteadOfBoundingBox = false;

        [SerializeField]
        [ShowIf(nameof(_useCollidersInsteadOfBoundingBox))]
        private List<Collider> _boundColliders;
```

Creates the following error in the Unity Inspector.

![image](https://user-images.githubusercontent.com/76707656/234234698-31ccc495-b39a-4688-8e17-a24d4932e287.png)

**Comment by GDGRhinox** [comment]
#37 Will fix this
