### ISSUE TITLE
ListDrawable inspector issue.

### ISSUE THREAD

**Issue by GlennQuintyn** [Rhinox-Training/rhinox-guiutils#42]
# Versions
`Unity: 2021.3.18f1 & 2021.3.22f1`
`GUIUtils: 2.10.0` (**CUSTOM**)  origin/ftr/chart-and-persistent-value-fixes
`Lightspeed: 1.5.11` (**CUSTOM**)  master

# Issue
When in the inspector you add items to a Listdrawable. Then remove anything but the last item in the list.
The drawing of the item coming after the just deleted item break. It shows just the {*namespace*}.{*NameOfClass*}.

**Comment by Bitpin** [comment]
Fixed in 2.11.1
